# Generated by Django 5.2.1 on 2025-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("th", models.IntegerField(default=0)),
                ("company", models.CharField(default="TBA", max_length=100)),
                ("contact", models.CharField(default="TBA", max_length=200)),
                ("introduce", models.TextField()),
                ("img", models.ImageField(upload_to="account/")),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
