# Generated by Django 5.2.1 on 2025-06-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Account",
            new_name="Alumini",
        ),
    ]
