# Generated by Django 5.2.1 on 2025-11-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="org/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
