# Generated by Django 5.2.1 on 2025-12-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpg", "0003_category_question_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="answer",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
